version: '3.3'
services:
  backend:
    build:
      context: ../
      dockerfile: backend.Dockerfile
    container_name: star-burger-backend
    restart: always
    volumes:
      - media_value:/app/media/
      - static_value:/app/static/
    env_file:
      - ../.env
    depends_on:
      - db
    command: gunicorn star_burger.wsgi:application --bind 0:8000
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ../
      dockerfile: frontend.Dockerfile
    container_name: star-burger-frontend
    command: ./node_modules/.bin/parcel watch ./bundles-src/index.js --dist-dir bundles --public-url "./"
    ports:
      - "1234:1234"

  db:
    image: postgres:13.0-alpine
    volumes:
      - db_value:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5432:5435"

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend

volumes:
  static_value:
  media_value:
  db_value:
