# Generated by Django 3.2.15 on 2022-12-22 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo_position', '0002_geoposition_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geoposition',
            name='type',
        ),
    ]
