# Generated by Django 3.2.15 on 2023-01-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_position', '0003_remove_geoposition_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoposition',
            name='address',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='адрес'),
        ),
    ]
