# Generated by Django 3.2.15 on 2023-01-20 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_position', '0004_alter_geoposition_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoposition',
            name='latitude',
            field=models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)], verbose_name='широта'),
        ),
        migrations.AlterField(
            model_name='geoposition',
            name='longitude',
            field=models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='долгота'),
        ),
    ]
