# Generated by Django 3.2.15 on 2022-12-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0038_order_orderdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='last_name',
            new_name='lastname',
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='quantity',
            field=models.SmallIntegerField(verbose_name='количество'),
        ),
    ]
