# Generated by Django 3.2.15 on 2022-12-20 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_order_phonenumber'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderDetail',
            new_name='OrderProducts',
        ),
    ]
