# Generated by Django 3.2.15 on 2022-12-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_order_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comments',
            field=models.TextField(blank=True, verbose_name='комментарий'),
        ),
    ]
