# Generated by Django 3.2.15 on 2022-12-21 08:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_auto_20221220_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('C', 'Наличными'), ('E', 'Электронно')], db_index=True, default='C', max_length=2, verbose_name='cпособ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='registered_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 12, 21, 8, 48, 39, 955746, tzinfo=utc), verbose_name='зарегистрирован'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('N', 'Необработанный'), ('C', 'Согласован с клиентом'), ('A', 'Собран'), ('D', 'В доставке'), ('F', 'Выполнен')], db_index=True, default='N', max_length=2, verbose_name='статус заказа'),
        ),
    ]
