# Generated by Django 3.2.15 on 2022-12-21 18:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_auto_20221221_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='restaurants',
            new_name='restaurant',
        ),
        migrations.AlterField(
            model_name='order',
            name='registered_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 12, 21, 18, 30, 8, 546106, tzinfo=utc), verbose_name='зарегистрирован'),
        ),
    ]
