# Generated by Django 3.2.15 on 2022-12-22 08:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_auto_20221221_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='registered_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 12, 22, 8, 14, 6, 513298, tzinfo=utc), verbose_name='зарегистрирован'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('N', 'Необработанный'), ('C', 'Изготавливается'), ('A', 'Собран'), ('D', 'В доставке'), ('F', 'Выполнен')], db_index=True, default='N', max_length=2, verbose_name='статус заказа'),
        ),
    ]
