# Generated by Django 3.2.15 on 2022-12-22 08:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_auto_20221222_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='registered_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 12, 22, 8, 54, 41, 816499, tzinfo=utc), verbose_name='зарегистрирован'),
        ),
    ]
