# Generated by Django 3.2.15 on 2022-12-23 20:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0056_alter_order_registered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличными'), ('electron', 'Электронно')], db_index=True, default='cash', max_length=10, verbose_name='cпособ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='registered_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 12, 23, 20, 16, 30, 689901, tzinfo=utc), verbose_name='зарегистрирован'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Необработанный'), ('make', 'Изготавливается'), ('assembled', 'Собран'), ('delievery', 'В доставке'), ('finish', 'Выполнен')], db_index=True, default='new', max_length=10, verbose_name='статус заказа'),
        ),
    ]
