# Generated by Django 3.2.15 on 2022-12-29 18:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0058_auto_20221229_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='registered_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 12, 29, 18, 49, 49, 692207, tzinfo=utc), verbose_name='зарегистрирован'),
        ),
    ]
