# Generated by Django 3.2.15 on 2023-01-20 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0061_auto_20230117_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_restaurant',
        ),
        migrations.AddField(
            model_name='order',
            name='cook_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foodcartapp.restaurant', verbose_name='приготовить в'),
        ),
    ]
